server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
      - id: flight-service
        uri: http://localhost:8082
        predicates:
          - Path=/api/v1/flights/**
      - id: customer-service
        uri: http://localhost:8081
        predicates:
          - Path=/api/v1/customers/**
        filters:
          - AddResponseHeader=My-Header-Good,Good
          - name: RequestRateLimiter
            args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
  application:
    name: edge-service
  redis:
    host: localhost
    port: 6379


opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics


logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG