server.port=8883
spring.application.name=email-service

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=email-group
spring.kafka.consumer.auto-offset-reset=earliest

app.kafka.topic-name=flight.email.topic


opentracing.jaeger.http-sender.url=http://localhost:14268/api/traces

management.endpoints.web.exposure.include=health, info, prometheus, metrics